# Generated by Django 3.2.9 on 2021-11-23 22:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20211123_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_column='email', max_length=254, null=True, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='group',
            field=models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.group', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, db_column='telefono', max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Ingrese un número de teléfono válido.', regex='^\\+?1?\\d{8,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(db_column='nombre', max_length=50, verbose_name='Nombre del grupo'),
        ),
    ]
